const {onCall,HttpsError}=require('firebase-functions/v2/https');
const {defineSecret}=require('firebase-functions/params');
const admin=require('firebase-admin');
admin.initializeApp();
const db=admin.firestore();
const GITHUB_TOKEN=defineSecret('GITHUB_TOKEN');
const CONFIG={owner:'my-future-letter',repo:'futureletter',branch:'main',pagesBase:'https://my-future-letter.github.io/futureletter',logo:'https://my-future-letter.github.io/futureletter/my-picture/my-future-letter-logo.png'};
function clean(s,max=100){return String(s||'').replace(/[<>]/g,'').slice(0,max)}
function b64(s){return Buffer.from(s,'utf8').toString('base64')}
async function gh(path,method='GET',body){const token=GITHUB_TOKEN.value();const r=await fetch(`https://api.github.com/repos/${CONFIG.owner}/${CONFIG.repo}/contents/${path}`,{method,headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2026-03-10'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw new HttpsError('failed-precondition',`GitHub API error ${r.status}: ${data.message||'Unknown error'}`);return data}
async function getSha(path){try{return (await gh(path)).sha}catch{return null}}
function publicHtml(bundle,meta){const title=clean(meta.title,140)||'My Future Letter';const author=clean(meta.author,100)||'Someone';const future=clean(meta.futureDate,40)||'the future';const desc=`A private future letter from ${author}, written today and waiting for ${future}. Unlock it with the letter password.`;return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} — My Future Letter</title><meta name="description" content="${desc}"><meta property="og:type" content="article"><meta property="og:site_name" content="My Future Letter"><meta property="og:title" content="${title} — My Future Letter"><meta property="og:description" content="${desc}"><meta property="og:image" content="${CONFIG.logo}"><meta property="og:url" content="${CONFIG.pagesBase}/futureletter/${encodeURIComponent(meta.username)}.html"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${title} — My Future Letter"><meta name="twitter:description" content="${desc}"><meta name="twitter:image" content="${CONFIG.logo}"><link rel="icon" href="${CONFIG.logo}"><link rel="stylesheet" href="../css/app.css"></head><body><header class="container nav"><a class="brand" href="../"><img src="${CONFIG.logo}"><span>My Future Letter<small>আমার ভবিষ্যতের চিঠি</small></span></a></header><main class="container locked" id="locked"><section class="card"><img class="logo-center" src="${CONFIG.logo}"><h1>A private letter is waiting.</h1><p class="muted">${author} wrote this letter for the future. Enter the letter password to unlock it.</p><div class="field"><label>Letter password</label><input id="password" type="password" autocomplete="current-password" placeholder="Enter password"></div><button class="btn primary" id="unlock">Unlock Letter</button><p id="msg" class="error"></p></section></main><article id="letter" class="future-letter hidden"><span class="badge">My Future Letter</span><h1 id="title"></h1><div class="meta"><span>From <b id="author"></b></span><span>For <b id="future"></b></span></div><hr style="border:0;border-top:1px solid #e5e9f2;margin:26px 0"><div id="content" class="content"></div><div class="notice" style="margin-top:30px">You are reading a password-protected Time Capsule. Keep the original PDF somewhere safe.</div></article><footer class="footer">My Future Letter · Write today. Meet yourself tomorrow.</footer><script>window.__MY_FUTURE_LETTER__=${JSON.stringify(bundle)};</script><script type="module" src="../js/public-letter.js"></script></body></html>`}
exports.claimUsername=onCall(async(req)=>{if(!req.auth)throw new HttpsError('unauthenticated','Please sign in first.');const username=clean(req.data.username,24).toLowerCase();if(!/^[a-z0-9]{3,24}$/.test(username))throw new HttpsError('invalid-argument','Username must be 3–24 letters/numbers.');const ref=db.doc(`usernames/${username}`);await db.runTransaction(async tx=>{const snap=await tx.get(ref);if(snap.exists&&snap.data().uid!==req.auth.uid)throw new HttpsError('already-exists','That username is already taken.');tx.set(ref,{uid:req.auth.uid,createdAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});tx.set(db.doc(`users/${req.auth.uid}`),{uid:req.auth.uid,name:clean(req.data.name,120),email:req.auth.token.email||'',username,createdAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true})});return {username}});
exports.uploadPhoto=onCall({secrets:[GITHUB_TOKEN],timeoutSeconds:120,memory:'512MiB'},async(req)=>{if(!req.auth)throw new HttpsError('unauthenticated','Sign in first.');const {photoId,base64}=req.data;const ext='jpg';if(!/^[a-zA-Z0-9_-]{6,20}$/.test(photoId||''))throw new HttpsError('invalid-argument','Invalid photo id.');if(typeof base64!=='string'||base64.length>7_000_000)throw new HttpsError('invalid-argument','Photo is too large.');const user=(await db.doc(`users/${req.auth.uid}`).get()).data();if(!user?.username)throw new HttpsError('failed-precondition','Create your username first.');const photos=await db.collection('photos').where('uid','==',req.auth.uid).get();if(photos.size>=25)throw new HttpsError('resource-exhausted','Maximum 25 photos per account.');const path=`picture/${user.username}/${photoId}.${ext}`;const sha=await getSha(path);await gh(path,'PUT',{message:`Add photo ${photoId}`,content:base64,branch:CONFIG.branch,sha:sha||undefined});const url=`${CONFIG.pagesBase}/${path}`;await db.doc(`photos/${photoId}`).set({uid:req.auth.uid,username:user.username,url,path,createdAt:admin.firestore.FieldValue.serverTimestamp()});return {url,path,photoId}});
exports.publishLetter=onCall({secrets:[GITHUB_TOKEN],timeoutSeconds:120},async(req)=>{if(!req.auth)throw new HttpsError('unauthenticated','Sign in first.');const {letterId,encrypted,meta}=req.data;const ref=db.doc(`letters/${letterId}`),snap=await ref.get();if(!snap.exists||snap.data().uid!==req.auth.uid)throw new HttpsError('permission-denied','You do not own this letter.');if(!encrypted?.data||!encrypted?.salt||!encrypted?.iv)throw new HttpsError('invalid-argument','Encrypted letter data is required.');const user=(await db.doc(`users/${req.auth.uid}`).get()).data();if(!user?.username||user.username!==meta.username)throw new HttpsError('permission-denied','Username mismatch.');const path=`futureletter/${user.username}.html`;const html=publicHtml(encrypted,{...meta,username:user.username});const sha=await getSha(path);await gh(path,'PUT',{message:`Publish My Future Letter ${user.username}`,content:b64(html),branch:CONFIG.branch,sha:sha||undefined});await ref.set({status:'published',encrypted,githubPath:path,publicUrl:`${CONFIG.pagesBase}/${path}`,updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});return {publicUrl:`${CONFIG.pagesBase}/futureletter/${user.username}.html`}});
exports.deleteLetter=onCall({secrets:[GITHUB_TOKEN],timeoutSeconds:120},async(req)=>{if(!req.auth)throw new HttpsError('unauthenticated','Sign in first.');const {letterId}=req.data;const ref=db.doc(`letters/${letterId}`),snap=await ref.get();if(!snap.exists||snap.data().uid!==req.auth.uid)throw new HttpsError('permission-denied','You do not own this letter.');const d=snap.data();if(d.githubPath){const sha=await getSha(d.githubPath);if(sha)await gh(d.githubPath,'DELETE',{message:`Delete My Future Letter ${d.username}`,sha,branch:CONFIG.branch})}await ref.delete();return {ok:true}});
exports.deletePhoto=onCall({secrets:[GITHUB_TOKEN],timeoutSeconds:120},async(req)=>{if(!req.auth)throw new HttpsError('unauthenticated','Sign in first.');const {photoId}=req.data;const ref=db.doc(`photos/${photoId}`),snap=await ref.get();if(!snap.exists||snap.data().uid!==req.auth.uid)throw new HttpsError('permission-denied','You do not own this photo.');const d=snap.data();const sha=await getSha(d.path);if(sha)await gh(d.path,'DELETE',{message:`Delete photo ${photoId}`,sha,branch:CONFIG.branch});await ref.delete();return {ok:true}});
